name: Auto Issue Identifier
on:
  issues:
    types: [labeled]
jobs:
  add-identifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get and update identifier
        id: get-id
        uses: actions/github-script@v7
        with:
          script: |
            const label = context.payload.label.name.toLowerCase();
            const prefix = {
              'bug': 'BUG',
              'enhancement': 'NFC',
              'duplicate': 'EFT'
            }[label];
            if (!prefix) {
              return;
            }
            
            // Get current counter from repository secret
            let counter;
            try {
              counter = JSON.parse(process.env[`ISSUE_COUNTERS`] || '{}');
            } catch (e) {
              counter = {};
            }
            
            // Initialize or increment counter for this prefix
            counter[prefix] = (counter[prefix] || 0) + 1;
            const newNum = counter[prefix].toString().padStart(3, '0');
            const newIdentifier = `${prefix}${newNum}`;
            
            // Save updated counter
            await github.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: 'ISSUE_COUNTERS',
              encrypted_value: Buffer.from(JSON.stringify(counter)).toString('base64')
            });
            
            // Update issue title
            const issue = context.payload.issue;
            const newTitle = `${newIdentifier}: ${issue.title}`;
            
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              title: newTitle
            });

permissions:
  issues: write
  contents: read
  actions: write
